# Generated by Django 2.1.3 on 2019-01-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import example.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('category', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=1000)),
                ('modification_date', models.DateField()),
                ('fileType', models.CharField(max_length=100)),
                ('file', example.models.EncryptedFileField(upload_to=example.models.generate_filename, verbose_name=models.CharField(max_length=100))),
                ('url', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key_validation', models.CharField(max_length=100)),
                ('date_key_given', models.DateField(null=True)),
                ('secret_key_given', models.CharField(max_length=140, null=True)),
                ('wants_deletion', models.BooleanField(default=False)),
                ('wants_download', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('category', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=1000)),
                ('modification_date', models.DateField()),
                ('fileType', models.CharField(max_length=100)),
                ('file', example.models.EncryptedFileField(upload_to='shared_files/', verbose_name=models.CharField(max_length=100))),
                ('nb_owners', models.IntegerField()),
                ('minimum_validation', models.IntegerField()),
                ('url', models.CharField(max_length=100, null=True)),
                ('users', models.ManyToManyField(through='example.Owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='shared_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.SharedFile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
