# Generated by Django 2.1.3 on 2018-12-27 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import example.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('modification_date', models.DateField()),
                ('fileType', models.CharField(max_length=100)),
                ('file', example.models.EncryptedFileField(upload_to='files/', verbose_name=models.CharField(max_length=100))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
