# Generated by Django 2.1.3 on 2019-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='secret_key_given',
            field=models.BinaryField(max_length=130, null=True),
        ),
    ]
