# Generated by Django 2.1.3 on 2019-01-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import example.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key_validation', models.CharField(max_length=100)),
                ('date_key_given', models.DateField(null=True)),
                ('secret_key_given', models.CharField(max_length=100, null=True)),
                ('wants_deletion', models.BooleanField(default=False)),
                ('wants_download', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('modification_date', models.DateField()),
                ('fileType', models.CharField(max_length=100)),
                ('file', example.models.EncryptedFileField(upload_to='shared_files/', verbose_name=models.CharField(max_length=100))),
                ('nb_owners', models.IntegerField()),
                ('owners', models.ManyToManyField(through='example.Owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=example.models.EncryptedFileField(upload_to=example.models.generate_filename, verbose_name=models.CharField(max_length=100)),
        ),
        migrations.AddField(
            model_name='owner',
            name='shared_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.SharedFile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
