# Generated by Django 2.1.3 on 2019-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190106_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='minimum_validation',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
