# Generated by Django 2.1.3 on 2019-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190108_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
