# Generated by Django 2.1.3 on 2019-01-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_sharedfile_minimum_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
