# Generated by Django 2.1.3 on 2019-01-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_auto_20190107_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='owners',
            new_name='users',
        ),
    ]
