# Generated by Django 2.1.3 on 2019-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20190107_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='secret_key_given',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
