# Generated by Django 2.1.3 on 2018-12-23 18:57

from django.db import migrations, models
import mysite.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileType',
            field=models.CharField(default='application/pdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=mysite.core.models.EncryptedFileField(upload_to='files/'),
        ),
    ]
